version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./drupal:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - backend
    ports:
      - "8080:80"
  backend:
    build: .
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./drupal:/var/www/html
    links:
      - database
  database:
    image: mysql
    env_file:
      - .env
    volumes:
    - database:/var/lib/mysql
volumes:
  database: